#dataloading configuration
name: imagenet_nas

s3_bucket: imagenet1k-sdl
s3_train_prefix: s3://imagenet1k-sdl/train/
s3_val_prefix: s3://imagenet1k-sdl/val/
num_pytorch_workers: 8

#model configuration
model_architecture: resnet18
learning_rate: 6e-4
weight_decay: 1e-1
precision: 32 # 16, 32, 64
num_classes: 1000
max_training_time_sec: null

max_dataset_size: null 
#training configuration
run_training: True
run_validation: False
validation_frequency: 1000000 #every n epochs
checkpoint_frequency: .inf #every n epochs
max_epochs: null
max_steps: null
batch_size: 128 #Number of samples between optimizer steps across data-parallel ranks
limit_train_batches: null
limit_val_batches: .inf
gpu_time: null