# conf/workload/cifar10_single_job.yaml
dataset_name: cifar10
dataset_path: data/cifar10/test
num_classes: 10
batch_size: 128
max_training_time_sec: null
max_training_steps: null
max_epochs: 3
precision: 32
# Global defaults
workload_type: single_job
job_id: 0
gpu_id: 0
model_name: resnet18
learning_rate: 6e-4
weight_decay: 1e-1
sim_gpu_time: 0.10
seed: null