#dataloading configuration
#dataloading configuration
name: cifar10
s3_bucket: sdl-cifar10
s3_train_prefix: s3://sdl-cifar10/train/
s3_val_prefix: s3://sdl-cifar10/val/
num_pytorch_workers: 0
max_dataset_size: null #5 #gb

#model configuration
model_architecture: resnet18
learning_rate: 6e-4
weight_decay: 1e-1
precision: 32 # 16, 32, 64
num_classes: 10
max_training_time_sec : null
#training configuration
run_training: True
run_validation: False
validation_frequency: 1000000 #every n epochs
checkpoint_frequency: .inf #every n epochs
max_epochs: 2
max_steps: 5000
batch_size: 128 #Number of samples between optimizer steps across data-parallel ranks
limit_train_batches: null
limit_val_batches: .inf
gpu_time: null #0.340841602