defaults:
  - _self_
  - workload: imagenet #imagenet, librispeech, coco, openimages
  
cache_address: 10.0.25.0:6378
enable_prefetching: False
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null


hydra:
  run:
    dir: .  # Current directory or a specific directory where Ray Tune expects to find it
  sweep:
    dir: .  # Same as above
  output_subdir: null
  job_logging:
    level: DISABLE  # Disable job-specific logging
  hydra_logging:
    level: DISABLE  # Disable Hydra-specific logging
