defaults:
  - _self_
  - workload: vision #text, vision, multimodal


lookahead_steps: 40
serverless_cache_address: 10.0.25.0:6378 # 10.0.21.36:6378 #redos-rdior4.serverless.usw2.cache.amazonaws.com:6379 #10.0.21.36:6378 #127.0.0.1:6379 #super-rdior4.serverless.usw2.cache.amazonaws.com:6379  #10.0.17.5:6378  #10.0.28.76:6378d 10.0.17.5:6378
cache_keep_alive_timeout: 60 #seconds
use_prefetching: True
use_keep_alive: True
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null

hydra:
  run:
    dir: .  # Current directory or a specific directory where Ray Tune expects to find it
  sweep:
    dir: .  # Same as above
  output_subdir: null
  job_logging:
    level: DISABLE  # Disable job-specific logging
  hydra_logging:
    level: DISABLE  # Disable Hydra-specific logging
