kind: 'coco'
batch_size: 128 #chunk_size  = number of files per chunk
shuffle: True
drop_last: False
prefetch_lambda_name: 'CreateMultiModalBatch'
max_dataset_size: null #gb
num_dataset_partitions: 1 
# num_dataset_partitions: 1