defaults:
  - _self_
  - dataloader: disdl #coordl, disdl, tensorsocket
  - workload: cifar10
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled  

accelerator: cpu                 # 'cpu', 'gpu', 'tpu'
devices: 1                       # Number of devices to use per job
log_interval: 1                  # Log every N steps
log_dir: logs
checkpoint_frequency: null
checkpoint_dir: null
simulation_mode: True            # Real training vs simulated
num_jobs: 1                   # Number of jobs to run
hydra:
  run:
    dir: .                      
  sweep:
    dir: .
  output_subdir: null
  job_logging:
    level: DISABLE
  hydra_logging:
    level: DISABLE