defaults:
  - _self_
  - dataloader: disdl #coordl, disdl, tensorsocket
  - workload: cifar10
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled  

seed: null 
num_jobs: 1
accelerator: gpu                 # 'cpu', 'gpu', 'tpu'
devices: 1                         # Number of devices to use per job
log_interval: 1                   # Log every N steps
log_dir: logs
checkpoint_dir: checkpoints

use_cache: False
cache_host: localhost
cache_port: 6379
ssl_enabled: False
                  # 16, 32, 64
simulation_mode: True            # Real training vs simulated
exp_id: single_job

job_id: 0

hydra:
  run:
    dir: .                         # Use current directory
  sweep:
    dir: .
  output_subdir: null
  job_logging:
    level: DISABLE
  hydra_logging:
    level: DISABLE