name: 'imagenet'
batch_size: 512 #chunk_size  = number of files per chunk
shuffle: True
drop_last: False
prefetch_lambda_name: 'CreateVisionTrainingBatch'
max_dataset_size: null #gb
num_partitions: 2
min_lookahead_steps: 100
dataset_location: s3://imagenet1k-sdl/train/